version: 0.2

phases:
  post_build:
    commands:
      # Create zip containing just your index.mjs
      - zip function.zip ecomm-lambda.mjs

artifacts:
  files:
    - 'function.zip'
    - 'appspec.yml'
  discard-paths: yes  # Ensures zip is at root level