version: 0.2

phases:
  post_build:
    commands:
      # Create zip containing just your index.mjs
      - zip function.zip index.mjs

artifacts:
  files:
    - 'function.zip'
  discard-paths: yes  # Ensures zip is at root level