version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - echo "Zipping the function"
      - zip -r function.zip index.mjs node_modules
      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name project-ecomm --zip-file fileb://function.zip  --region us-east-2

artifacts:
  files:
    - function.zip
